[package]
name = "tas2780"
version = "0.1.0"
edition = "2021"

[dependencies]
defmt = "0.3"

embassy-time = { version = "0.4.0", features = [
    "defmt",
    "defmt-timestamp-uptime",
] }

embedded-hal = "1.0"
