name: Rust build

on:
  workflow_call:
    inputs:
      target-directory:
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Format
        working-directory: ${{ inputs.target-directory }}
        run: cargo fmt
      - name: Lint
        working-directory: ${{ inputs.target-directory }}
        run: cargo clippy
      - name: Build
        working-directory: ${{ inputs.target-directory }}
        run: cargo build --verbose
      - name: Test
        working-directory: ${{ inputs.target-directory }}
        run: cargo test --verbose
