name: Rust build

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build
        run: bash .github/ci/build.sh

      - name: Cache build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            blus_mini_mk1
            blus_mini_mk2
            blackpill_pcm5102a

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            blackpill_pcm5102a/target/thumbv7em-none-eabihf/release/blackpill_pcm5102a
            blus_mini_mk2/target/thumbv7em-none-eabihf/release/blus_mini_mk2
