name: Rust build

on:
  push:
  pull_request:

jobs:
  build-blus-mini-mk1:
    uses: build.yml@main
    with:
      config-path: blus_mini_mk1

  build-blus-mini-mk2:
    uses: build.yml@main
    with:
      config-path: blus_mini_mk2
