name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Format
        working-directory: ./firmware
        run: cargo fmt
      - name: Lint
        working-directory: ./firmware
        run: cargo clippy
      - name: Build
        working-directory: ./firmware
        run: cargo build --verbose
      - name: Test
        working-directory: ./firmware
        run: cargo test --verbose
